#!/bin/sh

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$local_branch" = "master" ]; then
    reflog_message=$(git reflog -1)
    merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")
    if [ -z $merged_branch_name  ] || [ "$merged_branch_name" = "" ] || [ "$merged_branch_name" = "master" ]; then
        echo "Master merged into master."
    else
        package_json=$(git rev-parse --show-toplevel)/package.json
        if [ -f "$package_json" ]; then
            version_string=$(echo $merged_branch_name | grep -e '\-\(v\|V\)\(100\|010\|001\)$' -o)
            if [ -z $version_string  ] || [ "$version_string" = "" ]; then
                echo "No version bump."
            else
                if [ "$version_string" = "-v100" ] || [ "$version_string" = "-V100" ]; then
                    npm version major -m "Releasing version v%s"
                elif [ "$version_string" = "-v010" ] || [ "$version_string" = "-V010" ]; then
                    npm version minor -m "Releasing version v%s"
                else
                    npm version patch -m "Releasing version v%s"
                fi
                git push --tags
            fi
        else
            echo "No package.json available, version bump skipped."
        fi
        

    fi

fi
exit 0