#!/bin/sh

LC_ALL=C

CGH_PACKAGE_JSON_FILE=$(git rev-parse --show-toplevel)/package.json

if [[ -f "$CGH_PACKAGE_JSON_FILE" ]]; then

    CGH_BRANCH_NAME_CURRENT="$(git rev-parse --abbrev-ref HEAD)"

    if [ "$CGH_BRANCH_NAME_CURRENT" = "master" ] || [ "$CGH_BRANCH_NAME_CURRENT" = "main" ]; then
        merged_branch_name=$(git branch |grep -v "$CGH_BRANCH_NAME_CURRENT")
        echo "Merged branch name: $merged_branch_name"

        if [ -z $merged_branch_name  ] || [ "$merged_branch_name" = "" ] || [ "$merged_branch_name" = "master" ]  || [ "$merged_branch_name" = "main" ]; then
            echo "Master / main merged into master / main."
        else
            version_string=$(echo $merged_branch_name | grep -i '\-version\-\(major\|minor\|patch\|fix\)$' -o | tr '[:upper:]' '[:lower:]')
            if [ -z $version_string  ] || [ "$version_string" = "" ]; then
                echo "No version bump rule in branch name ${merged_branch_name}."
            else
                if [ "$version_string" = "-version-major" ]; then
                    npm version major -m "Releasing version %s"
                elif [ "$version_string" = "-version-minor" ]; then
                    npm version minor -m "Releasing version %s"
                else
                    npm version patch -m "Releasing version %s"
                fi
                git push --tags
                echo "Version bump released."
            fi
        fi
    else
        echo "No version bump, unless merged into  / main."
    fi
else
    echo "No package.json available, version bump skipped."
fi