#!/bin/sh

LC_ALL=C

cache_file=$(git rev-parse --show-toplevel)/.git/.cgh.variables
eval "$(./$cache_file)"

valid_branch_regex='^(?:[A-Z][A-Z]+-[0-9]+|NOJIRA)-[a-zA-Z0-9-]+$'

example_branch_name=${CGH_BRANCH_NAME_CURRENT//_/-}
example_branch_name=${example_branch_name//[^-\w]+/}
(  echo "$example_branch_name" | grep -Eq  "$valid_branch_regex" )  && regex_check="1" || regex_check="0"
if [ $regex_check = "0" ]
then
    example_branch_name="NOJIRA-$example_branch_name"
fi

msg_error="[ERROR]: There is something wrong with your new branch name: 

$CGH_BRANCH_NAME_CURRENT

Branch names in this project must adhere to this contract: 

$valid_branch_regex 

Your commit will be rejected. 

You should rename the branch so that it starts with the name of the JIRA card (eg: JIRA-1234) or the string NOJIRA,
contains only alphanumeric characters (0-9a-zA-Z) and hyphens (-) and try again, eg:

git branch -m NOJIRA-$example_branch_name
"

msg_notice="[NOTICE]: This (old) branch does not comply our branch name rules:

$valid_branch_regex

Rules: branch name starts with the name of the JIRA card (eg: JIRA-1234) or the string NOJIRA,
contains only alphanumeric characters (0-9a-zA-Z) and hyphens (-).

However: commit continues.
"

if [ "$CGH_BRANCH_NAME_CURRENT" = "master" ] || [ "$CGH_BRANCH_NAME_CURRENT" = "main" ]; then
    exec < /dev/tty
    while true; do
        read -p "[WARNING] Are You sure You want to commit into master / main? (y/N) " yn
        if [ "$yn" = "" ]; then
            yn='N'
        fi
        case $yn in
            [Yy] ) echo "Your answer is Yes: commit continues."; exit 0; break;;
            [Nn] ) echo "Your answer is No: commit is rejected."; exit 1;;
            * ) echo "Please answer y or n for yes or no.";;
        esac
    done
else
    (  echo "$CGH_BRANCH_NAME_CURRENT" | grep -Eq  "$valid_branch_regex" )  && regex_check="1" || regex_check="0"
    if [ -z "$CGH_LOG_QUERY" ]; then 
        
        if [ $regex_check = "0" ]
        then
            echo "$msg_error"
            exit 1
        fi
    else
        if [ $regex_check = "0" ]
        then
            echo "$msg_notice"
        fi
    fi
fi
exit 0