#!/bin/sh

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

jira_ticket=$(echo $local_branch | grep -e '^[A-Z][A-Z]\+-[0-9]\+\|NOJIRA' -o)
if [ -z $jira_ticket  ] || [ $jira_ticket = "" ]; then
    jira_ticket="NOJIRA"
fi
commit_check="${jira_ticket}: "

commit_orig_ticket=$(echo $1 | grep -e '^[A-Z][A-Z]\+-[0-9]\+\|NOJIRA' -o)

msg_notice="NOTICE: The JIRA card name ($commit_orig_ticket) for this commit message: 
$1 
is different from the JIRA card name ($jira_ticket) in the branch name: 
$local_branch"

if ! grep -iqE "^$commit_check" "$1"; then
    if [ -z $commit_orig_ticket  ] && [ "$commit_orig_ticket" != "" ]; then
        echo "$msg_notice"
    else
        echo "$jira_ticket"': '$(cat "$1") > "$1"
    fi
fi

exit 0
