#!/bin/sh

LC_ALL=C

cache_file=$(git rev-parse --show-toplevel)/.git/.cgh.variables
eval "$(./$cache_file)"

jira_ticket=$(echo $CGH_BRANCH_NAME_CURRENT| grep -e '^[A-Z][A-Z]\+-[0-9]\+\|NOJIRA' -o)
if [ -z $jira_ticket  ] || [ "$jira_ticket" = "" ]; then
    jira_ticket="NOJIRA"
fi
commit_check="${jira_ticket}: "

commit_orig_ticket=$(echo $CGH_COMMIT_MESSAGE | grep -e '^[A-Z][A-Z]\+-[0-9]\+\|NOJIRA' -o)

msg_notice="
NOTICE: The JIRA card name ($commit_orig_ticket) for this commit message: 
* $CGH_COMMIT_MESSAGE ($1) 
is different from the JIRA card name ($jira_ticket) in the branch name: 
* $CGH_BRANCH_NAME_CURRENT
"

if ! grep -iqE "^$commit_check" "$1"; then
    if [ -z $commit_orig_ticket  ] || [ "$commit_orig_ticket" = "" ]; then
        echo "$jira_ticket"': '$(cat "$1") > "$1"
    else
        echo "$msg_notice"
    fi
fi

exit 0

